production:
  adapter: postgresql
  encoding: unicode
  database: database_name
  pool: 5
  username: name_your_user
  password: password123

development:
  adapter: postgresql
  database: database_name

test:
  adapter: postgresql
  database: database_name
